#ifndef CCSDS_CONFIG_H_
#define CCSDS_CONFIG_H_

#define CCSDS_ENDIAN_BIG (0)
#define CCSDS_ENDIAN_LITTLE (1)

#ifndef CCSDS_CONFIG_ENDIAN
#define CCSDS_CONFIG_ENDIAN (CCSDS_ENDIAN_LITTLE)
#endif

#endif /* CCSDS_CONFIG_H_ */
